/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { ILendableProvider } from "../ILendableProvider";

export class ILendableProvider__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILendableProvider {
    return new Contract(address, _abi, signerOrProvider) as ILendableProvider;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "isRegisteredLendable",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
