/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IPairDeployer } from "../IPairDeployer";

export class IPairDeployer__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPairDeployer {
    return new Contract(address, _abi, signerOrProvider) as IPairDeployer;
  }
}

const _abi = [
  {
    inputs: [],
    name: "getPairImplementation",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];
