/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { Proxy } from "../Proxy";

export class Proxy__factory {
  static connect(address: string, signerOrProvider: Signer | Provider): Proxy {
    return new Contract(address, _abi, signerOrProvider) as Proxy;
  }
}

const _abi = [
  {
    stateMutability: "nonpayable",
    type: "fallback",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
];
