/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IPairFactoryInterface extends ethers.utils.Interface {
  functions: {
    "getAllProxyLendables()": FunctionFragment;
    "getAllShortables()": FunctionFragment;
    "getAllTradables()": FunctionFragment;
    "getOrCreatePair(address,address)": FunctionFragment;
    "getOrCreateRoutablePair(address,address,address)": FunctionFragment;
    "getOrCreateRoutableShortingPair(address,address,address)": FunctionFragment;
    "getOrCreateShortingPair(address,address)": FunctionFragment;
    "getPair(address,address)": FunctionFragment;
    "getRoutablePair(address,address,address)": FunctionFragment;
    "getRoutableShortingPair(address,address,address)": FunctionFragment;
    "getShortingPair(address,address)": FunctionFragment;
    "isPair(address)": FunctionFragment;
    "isRegisteredShortable(address)": FunctionFragment;
    "registerProxyLendable(address)": FunctionFragment;
    "registerProxyLendables(address[])": FunctionFragment;
    "registerShortable(address)": FunctionFragment;
    "registerShortables(address[])": FunctionFragment;
    "registerTradable(address)": FunctionFragment;
    "registerTradables(address[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getAllProxyLendables",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllShortables",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllTradables",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOrCreatePair",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrCreateRoutablePair",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrCreateRoutableShortingPair",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrCreateShortingPair",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getPair",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoutablePair",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoutableShortingPair",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getShortingPair",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "isPair", values: [string]): string;
  encodeFunctionData(
    functionFragment: "isRegisteredShortable",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerProxyLendable",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerProxyLendables",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "registerShortable",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerShortables",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "registerTradable",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerTradables",
    values: [string[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAllProxyLendables",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllShortables",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllTradables",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOrCreatePair",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOrCreateRoutablePair",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOrCreateRoutableShortingPair",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOrCreateShortingPair",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPair", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoutablePair",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoutableShortingPair",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getShortingPair",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isPair", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isRegisteredShortable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerProxyLendable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerProxyLendables",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerShortable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerShortables",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerTradable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerTradables",
    data: BytesLike
  ): Result;

  events: {};
}

export class IPairFactory extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IPairFactoryInterface;

  functions: {
    getAllProxyLendables(overrides?: Overrides): Promise<ContractTransaction>;

    "getAllProxyLendables()"(
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getAllShortables(overrides?: Overrides): Promise<ContractTransaction>;

    "getAllShortables()"(overrides?: Overrides): Promise<ContractTransaction>;

    getAllTradables(overrides?: Overrides): Promise<ContractTransaction>;

    "getAllTradables()"(overrides?: Overrides): Promise<ContractTransaction>;

    getOrCreatePair(
      lendable: string,
      tradable: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "getOrCreatePair(address,address)"(
      lendable: string,
      tradable: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getOrCreateRoutablePair(
      lendable: string,
      proxyLendable: string,
      tradable: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "getOrCreateRoutablePair(address,address,address)"(
      lendable: string,
      proxyLendable: string,
      tradable: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getOrCreateRoutableShortingPair(
      lendable: string,
      proxyLendable: string,
      tradable: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "getOrCreateRoutableShortingPair(address,address,address)"(
      lendable: string,
      proxyLendable: string,
      tradable: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getOrCreateShortingPair(
      lendable: string,
      tradable: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "getOrCreateShortingPair(address,address)"(
      lendable: string,
      tradable: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getPair(
      lendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "getPair(address,address)"(
      lendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getRoutablePair(
      lendable: string,
      proxyLendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "getRoutablePair(address,address,address)"(
      lendable: string,
      proxyLendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getRoutableShortingPair(
      lendable: string,
      proxyLendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "getRoutableShortingPair(address,address,address)"(
      lendable: string,
      proxyLendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getShortingPair(
      lendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "getShortingPair(address,address)"(
      lendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    isPair(pair: string, overrides?: CallOverrides): Promise<[boolean]>;

    "isPair(address)"(
      pair: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isRegisteredShortable(
      token: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "isRegisteredShortable(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    registerProxyLendable(
      token: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "registerProxyLendable(address)"(
      token: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    registerProxyLendables(
      tokens: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "registerProxyLendables(address[])"(
      tokens: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    registerShortable(
      token: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "registerShortable(address)"(
      token: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    registerShortables(
      tokens: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "registerShortables(address[])"(
      tokens: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    registerTradable(
      token: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "registerTradable(address)"(
      token: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    registerTradables(
      tokens: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "registerTradables(address[])"(
      tokens: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  getAllProxyLendables(overrides?: Overrides): Promise<ContractTransaction>;

  "getAllProxyLendables()"(overrides?: Overrides): Promise<ContractTransaction>;

  getAllShortables(overrides?: Overrides): Promise<ContractTransaction>;

  "getAllShortables()"(overrides?: Overrides): Promise<ContractTransaction>;

  getAllTradables(overrides?: Overrides): Promise<ContractTransaction>;

  "getAllTradables()"(overrides?: Overrides): Promise<ContractTransaction>;

  getOrCreatePair(
    lendable: string,
    tradable: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "getOrCreatePair(address,address)"(
    lendable: string,
    tradable: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getOrCreateRoutablePair(
    lendable: string,
    proxyLendable: string,
    tradable: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "getOrCreateRoutablePair(address,address,address)"(
    lendable: string,
    proxyLendable: string,
    tradable: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getOrCreateRoutableShortingPair(
    lendable: string,
    proxyLendable: string,
    tradable: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "getOrCreateRoutableShortingPair(address,address,address)"(
    lendable: string,
    proxyLendable: string,
    tradable: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getOrCreateShortingPair(
    lendable: string,
    tradable: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "getOrCreateShortingPair(address,address)"(
    lendable: string,
    tradable: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getPair(
    lendable: string,
    tradable: string,
    overrides?: CallOverrides
  ): Promise<string>;

  "getPair(address,address)"(
    lendable: string,
    tradable: string,
    overrides?: CallOverrides
  ): Promise<string>;

  getRoutablePair(
    lendable: string,
    proxyLendable: string,
    tradable: string,
    overrides?: CallOverrides
  ): Promise<string>;

  "getRoutablePair(address,address,address)"(
    lendable: string,
    proxyLendable: string,
    tradable: string,
    overrides?: CallOverrides
  ): Promise<string>;

  getRoutableShortingPair(
    lendable: string,
    proxyLendable: string,
    tradable: string,
    overrides?: CallOverrides
  ): Promise<string>;

  "getRoutableShortingPair(address,address,address)"(
    lendable: string,
    proxyLendable: string,
    tradable: string,
    overrides?: CallOverrides
  ): Promise<string>;

  getShortingPair(
    lendable: string,
    tradable: string,
    overrides?: CallOverrides
  ): Promise<string>;

  "getShortingPair(address,address)"(
    lendable: string,
    tradable: string,
    overrides?: CallOverrides
  ): Promise<string>;

  isPair(pair: string, overrides?: CallOverrides): Promise<boolean>;

  "isPair(address)"(pair: string, overrides?: CallOverrides): Promise<boolean>;

  isRegisteredShortable(
    token: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "isRegisteredShortable(address)"(
    token: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  registerProxyLendable(
    token: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "registerProxyLendable(address)"(
    token: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  registerProxyLendables(
    tokens: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "registerProxyLendables(address[])"(
    tokens: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  registerShortable(
    token: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "registerShortable(address)"(
    token: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  registerShortables(
    tokens: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "registerShortables(address[])"(
    tokens: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  registerTradable(
    token: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "registerTradable(address)"(
    token: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  registerTradables(
    tokens: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "registerTradables(address[])"(
    tokens: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    getAllProxyLendables(overrides?: CallOverrides): Promise<string[]>;

    "getAllProxyLendables()"(overrides?: CallOverrides): Promise<string[]>;

    getAllShortables(overrides?: CallOverrides): Promise<string[]>;

    "getAllShortables()"(overrides?: CallOverrides): Promise<string[]>;

    getAllTradables(overrides?: CallOverrides): Promise<string[]>;

    "getAllTradables()"(overrides?: CallOverrides): Promise<string[]>;

    getOrCreatePair(
      lendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "getOrCreatePair(address,address)"(
      lendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getOrCreateRoutablePair(
      lendable: string,
      proxyLendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "getOrCreateRoutablePair(address,address,address)"(
      lendable: string,
      proxyLendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getOrCreateRoutableShortingPair(
      lendable: string,
      proxyLendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "getOrCreateRoutableShortingPair(address,address,address)"(
      lendable: string,
      proxyLendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getOrCreateShortingPair(
      lendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "getOrCreateShortingPair(address,address)"(
      lendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getPair(
      lendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "getPair(address,address)"(
      lendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getRoutablePair(
      lendable: string,
      proxyLendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "getRoutablePair(address,address,address)"(
      lendable: string,
      proxyLendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getRoutableShortingPair(
      lendable: string,
      proxyLendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "getRoutableShortingPair(address,address,address)"(
      lendable: string,
      proxyLendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getShortingPair(
      lendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "getShortingPair(address,address)"(
      lendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<string>;

    isPair(pair: string, overrides?: CallOverrides): Promise<boolean>;

    "isPair(address)"(
      pair: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isRegisteredShortable(
      token: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "isRegisteredShortable(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    registerProxyLendable(
      token: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "registerProxyLendable(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<void>;

    registerProxyLendables(
      tokens: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    "registerProxyLendables(address[])"(
      tokens: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    registerShortable(token: string, overrides?: CallOverrides): Promise<void>;

    "registerShortable(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<void>;

    registerShortables(
      tokens: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    "registerShortables(address[])"(
      tokens: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    registerTradable(token: string, overrides?: CallOverrides): Promise<void>;

    "registerTradable(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<void>;

    registerTradables(
      tokens: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    "registerTradables(address[])"(
      tokens: string[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getAllProxyLendables(overrides?: Overrides): Promise<BigNumber>;

    "getAllProxyLendables()"(overrides?: Overrides): Promise<BigNumber>;

    getAllShortables(overrides?: Overrides): Promise<BigNumber>;

    "getAllShortables()"(overrides?: Overrides): Promise<BigNumber>;

    getAllTradables(overrides?: Overrides): Promise<BigNumber>;

    "getAllTradables()"(overrides?: Overrides): Promise<BigNumber>;

    getOrCreatePair(
      lendable: string,
      tradable: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "getOrCreatePair(address,address)"(
      lendable: string,
      tradable: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getOrCreateRoutablePair(
      lendable: string,
      proxyLendable: string,
      tradable: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "getOrCreateRoutablePair(address,address,address)"(
      lendable: string,
      proxyLendable: string,
      tradable: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getOrCreateRoutableShortingPair(
      lendable: string,
      proxyLendable: string,
      tradable: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "getOrCreateRoutableShortingPair(address,address,address)"(
      lendable: string,
      proxyLendable: string,
      tradable: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getOrCreateShortingPair(
      lendable: string,
      tradable: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "getOrCreateShortingPair(address,address)"(
      lendable: string,
      tradable: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getPair(
      lendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getPair(address,address)"(
      lendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoutablePair(
      lendable: string,
      proxyLendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getRoutablePair(address,address,address)"(
      lendable: string,
      proxyLendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoutableShortingPair(
      lendable: string,
      proxyLendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getRoutableShortingPair(address,address,address)"(
      lendable: string,
      proxyLendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getShortingPair(
      lendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getShortingPair(address,address)"(
      lendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isPair(pair: string, overrides?: CallOverrides): Promise<BigNumber>;

    "isPair(address)"(
      pair: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isRegisteredShortable(
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "isRegisteredShortable(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    registerProxyLendable(
      token: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "registerProxyLendable(address)"(
      token: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    registerProxyLendables(
      tokens: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "registerProxyLendables(address[])"(
      tokens: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    registerShortable(token: string, overrides?: Overrides): Promise<BigNumber>;

    "registerShortable(address)"(
      token: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    registerShortables(
      tokens: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "registerShortables(address[])"(
      tokens: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    registerTradable(token: string, overrides?: Overrides): Promise<BigNumber>;

    "registerTradable(address)"(
      token: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    registerTradables(
      tokens: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "registerTradables(address[])"(
      tokens: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getAllProxyLendables(overrides?: Overrides): Promise<PopulatedTransaction>;

    "getAllProxyLendables()"(
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getAllShortables(overrides?: Overrides): Promise<PopulatedTransaction>;

    "getAllShortables()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    getAllTradables(overrides?: Overrides): Promise<PopulatedTransaction>;

    "getAllTradables()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    getOrCreatePair(
      lendable: string,
      tradable: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "getOrCreatePair(address,address)"(
      lendable: string,
      tradable: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getOrCreateRoutablePair(
      lendable: string,
      proxyLendable: string,
      tradable: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "getOrCreateRoutablePair(address,address,address)"(
      lendable: string,
      proxyLendable: string,
      tradable: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getOrCreateRoutableShortingPair(
      lendable: string,
      proxyLendable: string,
      tradable: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "getOrCreateRoutableShortingPair(address,address,address)"(
      lendable: string,
      proxyLendable: string,
      tradable: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getOrCreateShortingPair(
      lendable: string,
      tradable: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "getOrCreateShortingPair(address,address)"(
      lendable: string,
      tradable: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getPair(
      lendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getPair(address,address)"(
      lendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoutablePair(
      lendable: string,
      proxyLendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getRoutablePair(address,address,address)"(
      lendable: string,
      proxyLendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoutableShortingPair(
      lendable: string,
      proxyLendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getRoutableShortingPair(address,address,address)"(
      lendable: string,
      proxyLendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getShortingPair(
      lendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getShortingPair(address,address)"(
      lendable: string,
      tradable: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isPair(
      pair: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isPair(address)"(
      pair: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isRegisteredShortable(
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isRegisteredShortable(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    registerProxyLendable(
      token: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "registerProxyLendable(address)"(
      token: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    registerProxyLendables(
      tokens: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "registerProxyLendables(address[])"(
      tokens: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    registerShortable(
      token: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "registerShortable(address)"(
      token: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    registerShortables(
      tokens: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "registerShortables(address[])"(
      tokens: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    registerTradable(
      token: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "registerTradable(address)"(
      token: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    registerTradables(
      tokens: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "registerTradables(address[])"(
      tokens: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
