/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IParamGovernanceInterface extends ethers.utils.Interface {
  functions: {
    "getAddress(bytes32)": FunctionFragment;
    "getFeeDistribution()": FunctionFragment;
    "getParam(bytes32)": FunctionFragment;
    "getParams()": FunctionFragment;
    "getVotes(address)": FunctionFragment;
    "revote(address)": FunctionFragment;
    "setAddress(bytes32,address)": FunctionFragment;
    "setParamBounds(bytes32,uint256,uint256)": FunctionFragment;
    "setParamsBounds(bytes32[],uint256[],uint256[])": FunctionFragment;
    "voteForFeeDistribution(address,tuple)": FunctionFragment;
    "voteForParam(address,bytes32,uint256)": FunctionFragment;
    "voteForParams(address,bytes32[],uint256[])": FunctionFragment;
    "xWOW()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getAddress",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getFeeDistribution",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getParam", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "getParams", values?: undefined): string;
  encodeFunctionData(functionFragment: "getVotes", values: [string]): string;
  encodeFunctionData(functionFragment: "revote", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setAddress",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setParamBounds",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setParamsBounds",
    values: [BytesLike[], BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "voteForFeeDistribution",
    values: [
      string,
      {
        governanceReward: BigNumberish;
        development: BigNumberish;
        insurance: BigNumberish;
        charity: BigNumberish;
        buyAndBurn: BigNumberish;
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "voteForParam",
    values: [string, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "voteForParams",
    values: [string, BytesLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(functionFragment: "xWOW", values?: undefined): string;

  decodeFunctionResult(functionFragment: "getAddress", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getFeeDistribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getParam", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getParams", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getVotes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "revote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setAddress", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setParamBounds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setParamsBounds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voteForFeeDistribution",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voteForParam",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voteForParams",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "xWOW", data: BytesLike): Result;

  events: {};
}

export class IParamGovernance extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IParamGovernanceInterface;

  functions: {
    getAddress(name: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    "getAddress(bytes32)"(
      name: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getFeeDistribution(
      overrides?: CallOverrides
    ): Promise<
      [string[], BigNumber[]] & { funds: string[]; percentages: BigNumber[] }
    >;

    "getFeeDistribution()"(
      overrides?: CallOverrides
    ): Promise<
      [string[], BigNumber[]] & { funds: string[]; percentages: BigNumber[] }
    >;

    getParam(name: BytesLike, overrides?: CallOverrides): Promise<[BigNumber]>;

    "getParam(bytes32)"(
      name: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getParams(overrides?: Overrides): Promise<ContractTransaction>;

    "getParams()"(overrides?: Overrides): Promise<ContractTransaction>;

    getVotes(
      holder: string,
      overrides?: CallOverrides
    ): Promise<
      [string[], BigNumber[]] & { names: string[]; values: BigNumber[] }
    >;

    "getVotes(address)"(
      holder: string,
      overrides?: CallOverrides
    ): Promise<
      [string[], BigNumber[]] & { names: string[]; values: BigNumber[] }
    >;

    revote(holder: string, overrides?: Overrides): Promise<ContractTransaction>;

    "revote(address)"(
      holder: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setAddress(
      name: BytesLike,
      value: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setAddress(bytes32,address)"(
      name: BytesLike,
      value: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setParamBounds(
      parameter: BytesLike,
      minValue: BigNumberish,
      maxValue: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setParamBounds(bytes32,uint256,uint256)"(
      parameter: BytesLike,
      minValue: BigNumberish,
      maxValue: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setParamsBounds(
      parameters: BytesLike[],
      minValues: BigNumberish[],
      maxValues: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setParamsBounds(bytes32[],uint256[],uint256[])"(
      parameters: BytesLike[],
      minValues: BigNumberish[],
      maxValues: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    voteForFeeDistribution(
      holder: string,
      distribution: {
        governanceReward: BigNumberish;
        development: BigNumberish;
        insurance: BigNumberish;
        charity: BigNumberish;
        buyAndBurn: BigNumberish;
      },
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "voteForFeeDistribution(address,(uint256,uint256,uint256,uint256,uint256))"(
      holder: string,
      distribution: {
        governanceReward: BigNumberish;
        development: BigNumberish;
        insurance: BigNumberish;
        charity: BigNumberish;
        buyAndBurn: BigNumberish;
      },
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    voteForParam(
      holder: string,
      name: BytesLike,
      value: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "voteForParam(address,bytes32,uint256)"(
      holder: string,
      name: BytesLike,
      value: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    voteForParams(
      holder: string,
      names: BytesLike[],
      values: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "voteForParams(address,bytes32[],uint256[])"(
      holder: string,
      names: BytesLike[],
      values: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    xWOW(overrides?: CallOverrides): Promise<[string]>;

    "xWOW()"(overrides?: CallOverrides): Promise<[string]>;
  };

  getAddress(name: BytesLike, overrides?: CallOverrides): Promise<string>;

  "getAddress(bytes32)"(
    name: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  getFeeDistribution(
    overrides?: CallOverrides
  ): Promise<
    [string[], BigNumber[]] & { funds: string[]; percentages: BigNumber[] }
  >;

  "getFeeDistribution()"(
    overrides?: CallOverrides
  ): Promise<
    [string[], BigNumber[]] & { funds: string[]; percentages: BigNumber[] }
  >;

  getParam(name: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

  "getParam(bytes32)"(
    name: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getParams(overrides?: Overrides): Promise<ContractTransaction>;

  "getParams()"(overrides?: Overrides): Promise<ContractTransaction>;

  getVotes(
    holder: string,
    overrides?: CallOverrides
  ): Promise<
    [string[], BigNumber[]] & { names: string[]; values: BigNumber[] }
  >;

  "getVotes(address)"(
    holder: string,
    overrides?: CallOverrides
  ): Promise<
    [string[], BigNumber[]] & { names: string[]; values: BigNumber[] }
  >;

  revote(holder: string, overrides?: Overrides): Promise<ContractTransaction>;

  "revote(address)"(
    holder: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setAddress(
    name: BytesLike,
    value: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setAddress(bytes32,address)"(
    name: BytesLike,
    value: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setParamBounds(
    parameter: BytesLike,
    minValue: BigNumberish,
    maxValue: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setParamBounds(bytes32,uint256,uint256)"(
    parameter: BytesLike,
    minValue: BigNumberish,
    maxValue: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setParamsBounds(
    parameters: BytesLike[],
    minValues: BigNumberish[],
    maxValues: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setParamsBounds(bytes32[],uint256[],uint256[])"(
    parameters: BytesLike[],
    minValues: BigNumberish[],
    maxValues: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  voteForFeeDistribution(
    holder: string,
    distribution: {
      governanceReward: BigNumberish;
      development: BigNumberish;
      insurance: BigNumberish;
      charity: BigNumberish;
      buyAndBurn: BigNumberish;
    },
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "voteForFeeDistribution(address,(uint256,uint256,uint256,uint256,uint256))"(
    holder: string,
    distribution: {
      governanceReward: BigNumberish;
      development: BigNumberish;
      insurance: BigNumberish;
      charity: BigNumberish;
      buyAndBurn: BigNumberish;
    },
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  voteForParam(
    holder: string,
    name: BytesLike,
    value: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "voteForParam(address,bytes32,uint256)"(
    holder: string,
    name: BytesLike,
    value: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  voteForParams(
    holder: string,
    names: BytesLike[],
    values: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "voteForParams(address,bytes32[],uint256[])"(
    holder: string,
    names: BytesLike[],
    values: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  xWOW(overrides?: CallOverrides): Promise<string>;

  "xWOW()"(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    getAddress(name: BytesLike, overrides?: CallOverrides): Promise<string>;

    "getAddress(bytes32)"(
      name: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    getFeeDistribution(
      overrides?: CallOverrides
    ): Promise<
      [string[], BigNumber[]] & { funds: string[]; percentages: BigNumber[] }
    >;

    "getFeeDistribution()"(
      overrides?: CallOverrides
    ): Promise<
      [string[], BigNumber[]] & { funds: string[]; percentages: BigNumber[] }
    >;

    getParam(name: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    "getParam(bytes32)"(
      name: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getParams(
      overrides?: CallOverrides
    ): Promise<
      ([string, BigNumber, BigNumber, BigNumber, BigNumber] & {
        name: string;
        value: BigNumber;
        amount: BigNumber;
        minValue: BigNumber;
        maxValue: BigNumber;
      })[]
    >;

    "getParams()"(
      overrides?: CallOverrides
    ): Promise<
      ([string, BigNumber, BigNumber, BigNumber, BigNumber] & {
        name: string;
        value: BigNumber;
        amount: BigNumber;
        minValue: BigNumber;
        maxValue: BigNumber;
      })[]
    >;

    getVotes(
      holder: string,
      overrides?: CallOverrides
    ): Promise<
      [string[], BigNumber[]] & { names: string[]; values: BigNumber[] }
    >;

    "getVotes(address)"(
      holder: string,
      overrides?: CallOverrides
    ): Promise<
      [string[], BigNumber[]] & { names: string[]; values: BigNumber[] }
    >;

    revote(holder: string, overrides?: CallOverrides): Promise<void>;

    "revote(address)"(holder: string, overrides?: CallOverrides): Promise<void>;

    setAddress(
      name: BytesLike,
      value: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setAddress(bytes32,address)"(
      name: BytesLike,
      value: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setParamBounds(
      parameter: BytesLike,
      minValue: BigNumberish,
      maxValue: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setParamBounds(bytes32,uint256,uint256)"(
      parameter: BytesLike,
      minValue: BigNumberish,
      maxValue: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setParamsBounds(
      parameters: BytesLike[],
      minValues: BigNumberish[],
      maxValues: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    "setParamsBounds(bytes32[],uint256[],uint256[])"(
      parameters: BytesLike[],
      minValues: BigNumberish[],
      maxValues: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    voteForFeeDistribution(
      holder: string,
      distribution: {
        governanceReward: BigNumberish;
        development: BigNumberish;
        insurance: BigNumberish;
        charity: BigNumberish;
        buyAndBurn: BigNumberish;
      },
      overrides?: CallOverrides
    ): Promise<void>;

    "voteForFeeDistribution(address,(uint256,uint256,uint256,uint256,uint256))"(
      holder: string,
      distribution: {
        governanceReward: BigNumberish;
        development: BigNumberish;
        insurance: BigNumberish;
        charity: BigNumberish;
        buyAndBurn: BigNumberish;
      },
      overrides?: CallOverrides
    ): Promise<void>;

    voteForParam(
      holder: string,
      name: BytesLike,
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "voteForParam(address,bytes32,uint256)"(
      holder: string,
      name: BytesLike,
      value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    voteForParams(
      holder: string,
      names: BytesLike[],
      values: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    "voteForParams(address,bytes32[],uint256[])"(
      holder: string,
      names: BytesLike[],
      values: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    xWOW(overrides?: CallOverrides): Promise<string>;

    "xWOW()"(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    getAddress(name: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    "getAddress(bytes32)"(
      name: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFeeDistribution(overrides?: CallOverrides): Promise<BigNumber>;

    "getFeeDistribution()"(overrides?: CallOverrides): Promise<BigNumber>;

    getParam(name: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    "getParam(bytes32)"(
      name: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getParams(overrides?: Overrides): Promise<BigNumber>;

    "getParams()"(overrides?: Overrides): Promise<BigNumber>;

    getVotes(holder: string, overrides?: CallOverrides): Promise<BigNumber>;

    "getVotes(address)"(
      holder: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    revote(holder: string, overrides?: Overrides): Promise<BigNumber>;

    "revote(address)"(
      holder: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setAddress(
      name: BytesLike,
      value: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setAddress(bytes32,address)"(
      name: BytesLike,
      value: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setParamBounds(
      parameter: BytesLike,
      minValue: BigNumberish,
      maxValue: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setParamBounds(bytes32,uint256,uint256)"(
      parameter: BytesLike,
      minValue: BigNumberish,
      maxValue: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setParamsBounds(
      parameters: BytesLike[],
      minValues: BigNumberish[],
      maxValues: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setParamsBounds(bytes32[],uint256[],uint256[])"(
      parameters: BytesLike[],
      minValues: BigNumberish[],
      maxValues: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    voteForFeeDistribution(
      holder: string,
      distribution: {
        governanceReward: BigNumberish;
        development: BigNumberish;
        insurance: BigNumberish;
        charity: BigNumberish;
        buyAndBurn: BigNumberish;
      },
      overrides?: Overrides
    ): Promise<BigNumber>;

    "voteForFeeDistribution(address,(uint256,uint256,uint256,uint256,uint256))"(
      holder: string,
      distribution: {
        governanceReward: BigNumberish;
        development: BigNumberish;
        insurance: BigNumberish;
        charity: BigNumberish;
        buyAndBurn: BigNumberish;
      },
      overrides?: Overrides
    ): Promise<BigNumber>;

    voteForParam(
      holder: string,
      name: BytesLike,
      value: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "voteForParam(address,bytes32,uint256)"(
      holder: string,
      name: BytesLike,
      value: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    voteForParams(
      holder: string,
      names: BytesLike[],
      values: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "voteForParams(address,bytes32[],uint256[])"(
      holder: string,
      names: BytesLike[],
      values: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    xWOW(overrides?: CallOverrides): Promise<BigNumber>;

    "xWOW()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getAddress(
      name: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getAddress(bytes32)"(
      name: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFeeDistribution(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getFeeDistribution()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getParam(
      name: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getParam(bytes32)"(
      name: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getParams(overrides?: Overrides): Promise<PopulatedTransaction>;

    "getParams()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    getVotes(
      holder: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getVotes(address)"(
      holder: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    revote(
      holder: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "revote(address)"(
      holder: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setAddress(
      name: BytesLike,
      value: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setAddress(bytes32,address)"(
      name: BytesLike,
      value: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setParamBounds(
      parameter: BytesLike,
      minValue: BigNumberish,
      maxValue: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setParamBounds(bytes32,uint256,uint256)"(
      parameter: BytesLike,
      minValue: BigNumberish,
      maxValue: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setParamsBounds(
      parameters: BytesLike[],
      minValues: BigNumberish[],
      maxValues: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setParamsBounds(bytes32[],uint256[],uint256[])"(
      parameters: BytesLike[],
      minValues: BigNumberish[],
      maxValues: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    voteForFeeDistribution(
      holder: string,
      distribution: {
        governanceReward: BigNumberish;
        development: BigNumberish;
        insurance: BigNumberish;
        charity: BigNumberish;
        buyAndBurn: BigNumberish;
      },
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "voteForFeeDistribution(address,(uint256,uint256,uint256,uint256,uint256))"(
      holder: string,
      distribution: {
        governanceReward: BigNumberish;
        development: BigNumberish;
        insurance: BigNumberish;
        charity: BigNumberish;
        buyAndBurn: BigNumberish;
      },
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    voteForParam(
      holder: string,
      name: BytesLike,
      value: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "voteForParam(address,bytes32,uint256)"(
      holder: string,
      name: BytesLike,
      value: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    voteForParams(
      holder: string,
      names: BytesLike[],
      values: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "voteForParams(address,bytes32[],uint256[])"(
      holder: string,
      names: BytesLike[],
      values: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    xWOW(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "xWOW()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
