/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface ReserveFactoryV1Interface extends ethers.utils.Interface {
  functions: {
    "REVISION()": FunctionFragment;
    "getAllLendables()": FunctionFragment;
    "getOrCreateReserve(address)": FunctionFragment;
    "getReserve(address)": FunctionFragment;
    "initialize(address,address)": FunctionFragment;
    "owner()": FunctionFragment;
    "registerLendable(address)": FunctionFragment;
    "registerLendables(address[])": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "reserveBytecodeHash()": FunctionFragment;
    "sweepFee(address,address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "REVISION", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getAllLendables",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOrCreateReserve",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "getReserve", values: [string]): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerLendable",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerLendables",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reserveBytecodeHash",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sweepFee",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "REVISION", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllLendables",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOrCreateReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getReserve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerLendable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerLendables",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reserveBytecodeHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sweepFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export class ReserveFactoryV1 extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: ReserveFactoryV1Interface;

  functions: {
    REVISION(overrides?: CallOverrides): Promise<[BigNumber]>;

    "REVISION()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    getAllLendables(overrides?: CallOverrides): Promise<[string[]]>;

    "getAllLendables()"(overrides?: CallOverrides): Promise<[string[]]>;

    getOrCreateReserve(
      lendable: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "getOrCreateReserve(address)"(
      lendable: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    getReserve(lendable: string, overrides?: CallOverrides): Promise<[string]>;

    "getReserve(address)"(
      lendable: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    initialize(
      poolFactory: string,
      paramProviderFactory: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "initialize(address,address)"(
      poolFactory: string,
      paramProviderFactory: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    "owner()"(overrides?: CallOverrides): Promise<[string]>;

    registerLendable(
      token: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "registerLendable(address)"(
      token: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    registerLendables(
      tokens: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "registerLendables(address[])"(
      tokens: string[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

    reserveBytecodeHash(overrides?: CallOverrides): Promise<[string]>;

    "reserveBytecodeHash()"(overrides?: CallOverrides): Promise<[string]>;

    sweepFee(
      lendable: string,
      to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "sweepFee(address,address)"(
      lendable: string,
      to: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  REVISION(overrides?: CallOverrides): Promise<BigNumber>;

  "REVISION()"(overrides?: CallOverrides): Promise<BigNumber>;

  getAllLendables(overrides?: CallOverrides): Promise<string[]>;

  "getAllLendables()"(overrides?: CallOverrides): Promise<string[]>;

  getOrCreateReserve(
    lendable: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "getOrCreateReserve(address)"(
    lendable: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  getReserve(lendable: string, overrides?: CallOverrides): Promise<string>;

  "getReserve(address)"(
    lendable: string,
    overrides?: CallOverrides
  ): Promise<string>;

  initialize(
    poolFactory: string,
    paramProviderFactory: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "initialize(address,address)"(
    poolFactory: string,
    paramProviderFactory: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  registerLendable(
    token: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "registerLendable(address)"(
    token: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  registerLendables(
    tokens: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "registerLendables(address[])"(
    tokens: string[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

  "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

  reserveBytecodeHash(overrides?: CallOverrides): Promise<string>;

  "reserveBytecodeHash()"(overrides?: CallOverrides): Promise<string>;

  sweepFee(
    lendable: string,
    to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "sweepFee(address,address)"(
    lendable: string,
    to: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    REVISION(overrides?: CallOverrides): Promise<BigNumber>;

    "REVISION()"(overrides?: CallOverrides): Promise<BigNumber>;

    getAllLendables(overrides?: CallOverrides): Promise<string[]>;

    "getAllLendables()"(overrides?: CallOverrides): Promise<string[]>;

    getOrCreateReserve(
      lendable: string,
      overrides?: CallOverrides
    ): Promise<string>;

    "getOrCreateReserve(address)"(
      lendable: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getReserve(lendable: string, overrides?: CallOverrides): Promise<string>;

    "getReserve(address)"(
      lendable: string,
      overrides?: CallOverrides
    ): Promise<string>;

    initialize(
      poolFactory: string,
      paramProviderFactory: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "initialize(address,address)"(
      poolFactory: string,
      paramProviderFactory: string,
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    registerLendable(
      token: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "registerLendable(address)"(
      token: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    registerLendables(
      tokens: string[],
      overrides?: CallOverrides
    ): Promise<boolean>;

    "registerLendables(address[])"(
      tokens: string[],
      overrides?: CallOverrides
    ): Promise<boolean>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    "renounceOwnership()"(overrides?: CallOverrides): Promise<void>;

    reserveBytecodeHash(overrides?: CallOverrides): Promise<string>;

    "reserveBytecodeHash()"(overrides?: CallOverrides): Promise<string>;

    sweepFee(
      lendable: string,
      to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "sweepFee(address,address)"(
      lendable: string,
      to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;
  };

  estimateGas: {
    REVISION(overrides?: CallOverrides): Promise<BigNumber>;

    "REVISION()"(overrides?: CallOverrides): Promise<BigNumber>;

    getAllLendables(overrides?: CallOverrides): Promise<BigNumber>;

    "getAllLendables()"(overrides?: CallOverrides): Promise<BigNumber>;

    getOrCreateReserve(
      lendable: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "getOrCreateReserve(address)"(
      lendable: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    getReserve(lendable: string, overrides?: CallOverrides): Promise<BigNumber>;

    "getReserve(address)"(
      lendable: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      poolFactory: string,
      paramProviderFactory: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "initialize(address,address)"(
      poolFactory: string,
      paramProviderFactory: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    registerLendable(token: string, overrides?: Overrides): Promise<BigNumber>;

    "registerLendable(address)"(
      token: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    registerLendables(
      tokens: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "registerLendables(address[])"(
      tokens: string[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    renounceOwnership(overrides?: Overrides): Promise<BigNumber>;

    "renounceOwnership()"(overrides?: Overrides): Promise<BigNumber>;

    reserveBytecodeHash(overrides?: CallOverrides): Promise<BigNumber>;

    "reserveBytecodeHash()"(overrides?: CallOverrides): Promise<BigNumber>;

    sweepFee(
      lendable: string,
      to: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "sweepFee(address,address)"(
      lendable: string,
      to: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    REVISION(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "REVISION()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getAllLendables(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getAllLendables()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getOrCreateReserve(
      lendable: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "getOrCreateReserve(address)"(
      lendable: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    getReserve(
      lendable: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getReserve(address)"(
      lendable: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      poolFactory: string,
      paramProviderFactory: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "initialize(address,address)"(
      poolFactory: string,
      paramProviderFactory: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    registerLendable(
      token: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "registerLendable(address)"(
      token: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    registerLendables(
      tokens: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "registerLendables(address[])"(
      tokens: string[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    renounceOwnership(overrides?: Overrides): Promise<PopulatedTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    reserveBytecodeHash(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "reserveBytecodeHash()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    sweepFee(
      lendable: string,
      to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "sweepFee(address,address)"(
      lendable: string,
      to: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
