name: docker_deploy

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: prod
      DOCKER_BUILDKIT: 1

    steps:
      - uses: actions/checkout@v2
      - name: Set environment variables
        run: |
          # Short name for current branch. For PRs, use target branch (base ref)
          GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}
          GIT_BRANCH=${GIT_BRANCH//\//_} # Replace / with _
          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV

      # Setup dependencies access
      - run: |
          npm config set //npm.pkg.github.com/:_authToken $TOKEN
          npm config set @wowswap-io:registry https://npm.pkg.github.com/
        env:
          TOKEN: ${{secrets.WOWSWAPCI_NPM_TOKEN}}

      # Enable Docker layer caching. Restores cache and saves layers after job finished
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true

      - name: Build image
        run: docker build --secret id=npmrc,src=$HOME/.npmrc --tag liquidation-bot:$GIT_BRANCH .

      - name: Push to ECR
        id: ecr
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-2
          image: liquidation-bot:$GIT_BRANCH

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Push to Docker Hub
        run: docker image tag liquidation-bot:$GIT_BRANCH wowswap/liquidation-bot:$GIT_BRANCH && docker push wowswap/liquidation-bot:$GIT_BRANCH
